#!/bin/bash

#This script moves all files and directories from a shared directory to Home, removes files' execution permissions recursively, and echos all top-level names to the terminal.

cd /media/sf_shared || exit

DESTIN=$HOME

for filename in *; do
 [ -e "$filename" ] || continue
 mv "$filename" "$DESTIN"
 if [ -f "$DESTIN/$filename" ]; then
  chmod a-x "$DESTIN/$filename"
 elif [ -d "$DESTIN/$filename" ]; then
  lsnes=$(ls -RQ "$DESTIN/$filename")
  k=2
  while true; do
   finame=$(echo $lsnes | cut -d '"' -f $k)
   if [ -z "$finame" ]; then
    break
   fi
   if [ -d "$finame" ]; then
    dirname=$finame
   elif [ -f "$dirname/$finame" ]; then
    chmod a-x "$dirname/$finame"
   fi
   k=$((k+2))
  done
 fi
 echo "$filename"
done
